name: NaverMapRankCheck

on:
  schedule:
    # 1. 오전 8시 45분 (UTC 23:45) -> 10시 출근 전 안정적 수신용
    - cron: '45 23 * * *'
    # 2. 오전 9시 30분 (UTC 00:30) -> 9시 정각 혼잡 피한 예비용
    - cron: '30 0 * * *'
    # 3. 오후 1시, 5시, 7시 (UTC 04:00, 08:00, 10:00)
    - cron: '0 4,8,10 * * *'
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FRIEND_CHAT_ID: ${{ secrets.FRIEND_CHAT_ID }}
        run: |
          pip install requests pytz beautifulsoup4
          python rank_check.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_rank.txt || true
          git commit -m "Update last rank" || exit 0
          git push
